kind: pipeline
type: docker
name: default

trigger:
  branch:
  - main
  event:
  - push

steps:
- name: webhook
  image: ghcr.io/appvia/drone-plugin
  settings:
    profile: local
    api_url: https://api-18-116-99-62.go.wayfinder.run
    username: localadmin
    password:
      from_secret: wayfinder-localadmin-password
    workspace: test
    args: whoami
